version: '3.8'

services:
  audio-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-service
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8000:8000"  # Adjust the port based on what your service exposes
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # Add any environment variables your service needs
      # - ENV_VAR_NAME=value
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge