services:
  audio-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-service
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./exported_models:/app/exported_models  # Add exported models volume
      - /dev/snd:/dev/snd  # Mount audio devices for audio recording
    ports:
      - "50051:50051"  # Changed from 8000 to 50051 for gRPC
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - GRPC_PORT=50051  # Set gRPC port environment variable
    networks:
      - audio-network
    devices:
      - /dev/snd  # Grant access to audio devices
    privileged: false  # Keep security but allow audio access
    cap_add:
      - SYS_NICE  # Allow audio priority adjustments

networks:
  audio-network:
    driver: bridge